version: '3.8'

networks:
  phostrich_network:
    driver: bridge

services:
  app:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    image: phostrich-srv
    container_name: phostrich-srv
    restart: unless-stopped
    ports:
      - "19000:9000" # Expose on port 9000
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - phostrich_network
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9080:80" # Expose Nginx on port 8080 for reverse proxy setup
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - phostrich_network
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: phostrich_postgres
    environment:
      POSTGRES_USER: phostrich
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: phostrich
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U phostrich" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phostrich_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: phostrich_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@phostrich.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - phostrich_network

  cache:
    image: redis/redis-stack:latest
    container_name: phostrich_redis
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phostrich_network

volumes:
  postgres_data:
    name: phostrich_postgres_data
    driver: local
  pgadmin_data:
    name: phostrich_pgadmin_data
  redis_data:
    name: phostrich_redis_data
